namespace NetEscapades.EnumGenerators
{
    /// <summary>
    /// Add to an assembly to indicate that usages of the enum should
    /// be automatically intercepted to use the extension methods
    /// generated by EnumExtensionsAttribute in this project.
    /// Note that the extension methods must be accessible from this project,
    /// otherwise you will receive compilation errors
    /// </summary>
    [System.AttributeUsage(System.AttributeTargets.Assembly, AllowMultiple = true)]
    [System.Diagnostics.Conditional("NETESCAPADES_ENUMGENERATORS_USAGES")]
    public class InterceptableAttribute<T> : System.Attribute
        where T: System.Enum
    {
        /// <summary>
        /// The namespace generated for the extension class. If not provided,
        /// and the referenced enum is in a different project, the namespace
        /// of the extension methods are assumed to be the same as the enum.
        /// </summary>
        public string? ExtensionClassNamespace { get; set; }

        /// <summary>
        /// The name used for the extension class. If not provided,
        /// and the referenced enum is in a different project, the enum name
        /// with an <c>Extensions</c> suffix will be assumed. For example for
        /// an Enum called StatusCodes, the assumed name will be StatusCodesExtensions.
        /// </summary>
        public string? ExtensionClassName { get; set; }
    }
}
