// //------------------------------------------------------------------------------
// // <auto-generated>
// //     This code was generated by the NetEscapades.EnumGenerators source generator
// //
// //     Changes to this file may cause incorrect behavior and will be lost if
// //     the code is regenerated.
// // </auto-generated>
// //------------------------------------------------------------------------------
//
// #nullable enable
//
// using System;
//
// namespace NetEscapades.EnumGenerators.IntegrationTests
// {
//     public enum EnumInNamespace2
//     {
//         First = 0,
//         Second = 1,
//         Third = 2,
//     }
//
// #pragma warning disable CS0612 // Ignore usages of obsolete members or enums
// #pragma warning disable CS0618 // Ignore usages of obsolete members or enums
//     /// <summary>
//     /// Extension methods for <see cref="global::NetEscapades.EnumGenerators.IntegrationTests.EnumInNamespace2" />
//     /// </summary>
//     [global::System.CodeDom.Compiler.GeneratedCodeAttribute("NetEscapades.EnumGenerators", "1.0.0-beta14")]
//     public static partial class Testing
//     {
//         /// <summary>
//         /// The number of members in the enum.
//         /// This is a non-distinct count of defined names.
//         /// </summary>
//         public const int Length = 3;
//
//         /// <summary>
//         /// Returns the string representation of the <see cref="global::NetEscapades.EnumGenerators.IntegrationTests.EnumInNamespace2"/> value.
//         /// If the attribute is decorated with a <c>[Display]</c> or <c>[Description]</c>attribute, then
//         /// uses the provided value. Otherwise uses the name of the member, equivalent to
//         /// calling <c>ToString()</c> on <paramref name="value"/>.
//         /// </summary>
//         /// <param name="value">The value to retrieve the string value for</param>
//         /// <param name="useMetadataAttributes">If <see langword="true"/> uses the value provided in the
//         /// <c>[Display]</c> or <c>[Description]</c>attribute as the string representation of the member.
//         /// If <see langword="false"/>, always uses the name of the member, the same as if <c>ToString()</c> was called.</param>
//         /// <returns>The string representation of the value</returns>
//         public static string ToStringFast(this global::NetEscapades.EnumGenerators.IntegrationTests.EnumInNamespace2 value, bool useMetadataAttributes)
//             => useMetadataAttributes ? value.ToStringFastWithMetadata() : value.ToStringFast();
//
//         public static string ToStringFast(
//             this global::NetEscapades.EnumGenerators.IntegrationTests.EnumInNamespace2 value,
//             global::NetEscapades.EnumGenerators.ToStringFastTransform transform,
//             global::NetEscapades.EnumGenerators.MetadataSource source)
//             => source switch
//             {
//                 MetadataSource.None => ToStringFastTransform.,
//                 MetadataSource.DisplayAttribute =>,
//                 MetadataSource.DescriptionAttribute =>,
//             };
//
//         /// <summary>
//         /// Returns the string representation of the <see cref="global::NetEscapades.EnumGenerators.IntegrationTests.EnumInNamespace2"/> value.
//         /// Directly equivalent to calling <c>ToString()</c> on <paramref name="value"/>.
//         /// </summary>
//         /// <param name="value">The value to retrieve the string value for</param>
//         /// <returns>The string representation of the value, the same as that returned by <c>ToString()</c></returns>
//         public static string ToStringFast(this global::NetEscapades.EnumGenerators.IntegrationTests.EnumInNamespace2 value)
//             => value switch
//             {
//                 global::NetEscapades.EnumGenerators.IntegrationTests.EnumInNamespace2.First => nameof(global::NetEscapades.EnumGenerators.IntegrationTests.EnumInNamespace2.First),
//                 global::NetEscapades.EnumGenerators.IntegrationTests.EnumInNamespace2.Second => nameof(global::NetEscapades.EnumGenerators.IntegrationTests.EnumInNamespace2.Second),
//                 global::NetEscapades.EnumGenerators.IntegrationTests.EnumInNamespace2.Third => nameof(global::NetEscapades.EnumGenerators.IntegrationTests.EnumInNamespace2.Third),
//                 _ => value.AsUnderlyingType().ToString(),
//             };
//
//         private static string ToStringFastWithMetadata(this global::NetEscapades.EnumGenerators.IntegrationTests.EnumInNamespace2 value)
//             => value.ToStringFast();
//
//         /// <summary>
//         /// Cast a value of <see cref="global::NetEscapades.EnumGenerators.IntegrationTests.EnumInNamespace2" /> to the underlying type (<c>int</c>).
//         /// This is mainly a convenience method.
//         /// </summary>
//         /// <returns>The value of <see cref="global::NetEscapades.EnumGenerators.IntegrationTests.EnumInNamespace2" /> cast to the underlying type.</returns>
//         public static int AsUnderlyingType(this global::NetEscapades.EnumGenerators.IntegrationTests.EnumInNamespace2 value)
//         {
//             return (int) value;
//         }
//
//         // C#14 Extension member syntax
//         // extension(global::NetEscapades.EnumGenerators.IntegrationTests.EnumInNamespace2)
//         // {
//
//         /// <summary>
//         /// Returns a boolean telling whether the given enum value exists in the enumeration.
//         /// </summary>
//         /// <param name="value">The value to check if it's defined</param>
//         /// <returns><see langword="true"/> if the value exists in the enumeration, <see langword="false"/> otherwise</returns>
//         public static bool IsDefined(global::NetEscapades.EnumGenerators.IntegrationTests.EnumInNamespace2 value)
//             => value switch
//             {
//                 global::NetEscapades.EnumGenerators.IntegrationTests.EnumInNamespace2.First => true,
//                 global::NetEscapades.EnumGenerators.IntegrationTests.EnumInNamespace2.Second => true,
//                 global::NetEscapades.EnumGenerators.IntegrationTests.EnumInNamespace2.Third => true,
//                 _ => false,
//             };
//
//         /// <summary>
//         /// Returns a boolean telling whether an enum with the given name exists in the enumeration.
//         /// </summary>
//         /// <param name="name">The name to check if it's defined</param>
//         /// <returns><see langword="true"/> if a member with the name exists in the enumeration, <see langword="false"/> otherwise</returns>
//         public static bool IsDefined(string name) => IsDefined(name, allowMatchingMetadataAttribute: false);
//
//         /// <summary>
//         /// Returns a boolean telling whether an enum with the given name exists in the enumeration,
//         /// or if a member decorated with a <c>[Display]</c> attribute
//         /// with the required name exists.
//         /// </summary>
//         /// <param name="name">The name to check if it's defined</param>
//         /// <param name="allowMatchingMetadataAttribute">If <see langword="true"/>, considers the value of metadata attributes,otherwise ignores them</param>
//         /// <returns><see langword="true"/> if a member with the name exists in the enumeration, or a member is decorated
//         /// with a <c>[Display]</c> attribute with the name, <see langword="false"/> otherwise</returns>
//         public static bool IsDefined(string name, bool allowMatchingMetadataAttribute)
//         {
//             return name switch
//             {
//                 nameof(global::NetEscapades.EnumGenerators.IntegrationTests.EnumInNamespace2.First) => true,
//                 nameof(global::NetEscapades.EnumGenerators.IntegrationTests.EnumInNamespace2.Second) => true,
//                 nameof(global::NetEscapades.EnumGenerators.IntegrationTests.EnumInNamespace2.Third) => true,
//                 _ => false,
//             };
//         }
//
//         /// <summary>
//         /// Returns a boolean telling whether an enum with the given name exists in the enumeration
//         /// </summary>
//         /// <param name="name">The name to check if it's defined</param>
//         /// <returns><see langword="true"/> if a member with the name exists in the enumeration, <see langword="false"/> otherwise</returns>
//         public static bool IsDefined(in global::System.ReadOnlySpan<char> name) => IsDefined(name, allowMatchingMetadataAttribute: false);
//
//         /// <summary>
//         /// Returns a boolean telling whether an enum with the given name exists in the enumeration,
//         /// or optionally if a member decorated with a <c>[Display]</c> attribute
//         /// with the required name exists.
//         /// Slower then the <see cref="IsDefined(string, bool)" /> overload, but doesn't allocate memory./>
//         /// </summary>
//         /// <param name="name">The name to check if it's defined</param>
//         /// <param name="allowMatchingMetadataAttribute">If <see langword="true"/>, considers the value of metadata attributes,otherwise ignores them</param>
//         /// <returns><see langword="true"/> if a member with the name exists in the enumeration, or a member is decorated
//         /// with a <c>[Display]</c> attribute with the name, <see langword="false"/> otherwise</returns>
//         public static bool IsDefined(in global::System.ReadOnlySpan<char> name, bool allowMatchingMetadataAttribute)
//         {
//             return name switch
//             {
//                 global::System.ReadOnlySpan<char> current when global::System.MemoryExtensions.Equals(current, nameof(global::NetEscapades.EnumGenerators.IntegrationTests.EnumInNamespace2.First), global::System.StringComparison.Ordinal) => true,
//                 global::System.ReadOnlySpan<char> current when global::System.MemoryExtensions.Equals(current, nameof(global::NetEscapades.EnumGenerators.IntegrationTests.EnumInNamespace2.Second), global::System.StringComparison.Ordinal) => true,
//                 global::System.ReadOnlySpan<char> current when global::System.MemoryExtensions.Equals(current, nameof(global::NetEscapades.EnumGenerators.IntegrationTests.EnumInNamespace2.Third), global::System.StringComparison.Ordinal) => true,
//                 _ => false,
//             };
//         }
//
//         /// <summary>
//         /// Converts the string representation of the name or numeric value of
//         /// an <see cref="global::NetEscapades.EnumGenerators.IntegrationTests.EnumInNamespace2" /> to the equivalent instance.
//         /// </summary>
//         /// <param name="name">The case-sensitive string representation of the enumeration name or underlying value to convert</param>
//         /// <returns>An object of type <see cref="global::NetEscapades.EnumGenerators.IntegrationTests.EnumInNamespace2" /> whose
//         /// value is represented by <paramref name="name"/></returns>
//         public static global::NetEscapades.EnumGenerators.IntegrationTests.EnumInNamespace2 Parse(
// #if NETCOREAPP3_0_OR_GREATER
//             [global::System.Diagnostics.CodeAnalysis.NotNullWhen(true)]
// #endif
//             string? name)
//                 => TryParse(name, out var value, false, false) ? value : ThrowValueNotFound(name);
//
//         /// <summary>
//         /// Converts the string representation of the name or numeric value of
//         /// an <see cref="global::NetEscapades.EnumGenerators.IntegrationTests.EnumInNamespace2" /> to the equivalent instance.
//         /// </summary>
//         /// <param name="name">The case-sensitive string representation of the enumeration name or underlying value to convert</param>
//         /// <param name="ignoreCase"><see langword="true"/> to read value in case insensitive mode; <see langword="false"/> to read value in case sensitive mode.</param>
//         /// <returns>An object of type <see cref="global::NetEscapades.EnumGenerators.IntegrationTests.EnumInNamespace2" /> whose
//         /// value is represented by <paramref name="name"/></returns>
//         public static global::NetEscapades.EnumGenerators.IntegrationTests.EnumInNamespace2 Parse(
// #if NETCOREAPP3_0_OR_GREATER
//             [global::System.Diagnostics.CodeAnalysis.NotNullWhen(true)]
// #endif
//             string? name,
//             bool ignoreCase)
//                 => TryParse(name, out var value, ignoreCase, false) ? value : ThrowValueNotFound(name);
//
//         /// <summary>
//         /// Converts the string representation of the name or numeric value of
//         /// an <see cref="global::NetEscapades.EnumGenerators.IntegrationTests.EnumInNamespace2" /> to the equivalent instance.
//         /// </summary>
//         /// <param name="name">The case-sensitive string representation of the enumeration name or underlying value to convert</param>
//         /// <param name="ignoreCase"><see langword="true"/> to read value in case insensitive mode; <see langword="false"/> to read value in case sensitive mode.</param>
//         /// <param name="allowMatchingMetadataAttribute">If <see langword="true"/>, considers the value included in metadata attributes such as
//         /// <c>[Display]</c> attribute when parsing, otherwise only considers the member names.</param>
//         /// <returns>An object of type <see cref="global::NetEscapades.EnumGenerators.IntegrationTests.EnumInNamespace2" /> whose
//         /// value is represented by <paramref name="name"/></returns>
//         public static global::NetEscapades.EnumGenerators.IntegrationTests.EnumInNamespace2 Parse(
// #if NETCOREAPP3_0_OR_GREATER
//             [global::System.Diagnostics.CodeAnalysis.NotNullWhen(true)]
// #endif
//             string? name,
//             bool ignoreCase,
//             bool allowMatchingMetadataAttribute)
//                 => TryParse(name, out var value, ignoreCase, allowMatchingMetadataAttribute) ? value : ThrowValueNotFound(name);
//
// #if NETCOREAPP3_0_OR_GREATER
//         [global::System.Diagnostics.CodeAnalysis.DoesNotReturn]
// #endif
//         private static global::NetEscapades.EnumGenerators.IntegrationTests.EnumInNamespace2 ThrowValueNotFound(string? name)
//             => throw new global::System.ArgumentException($"Requested value '{name}' was not found.");
//
//         /// <summary>
//         /// Converts the string representation of the name or numeric value of
//         /// an <see cref="global::NetEscapades.EnumGenerators.IntegrationTests.EnumInNamespace2" /> to the equivalent instance.
//         /// The return value indicates whether the conversion succeeded.
//         /// </summary>
//         /// <param name="name">The case-sensitive string representation of the enumeration name or underlying value to convert</param>
//         /// <param name="value">When this method returns, contains an object of type
//         /// <see cref="global::NetEscapades.EnumGenerators.IntegrationTests.EnumInNamespace2" /> whose
//         /// value is represented by <paramref name="value"/> if the parse operation succeeds.
//         /// If the parse operation fails, contains the default value of the underlying type
//         /// of <see cref="global::NetEscapades.EnumGenerators.IntegrationTests.EnumInNamespace2" />. This parameter is passed uninitialized.</param>
//         /// <returns><see langword="true"/> if the value parameter was converted successfully; otherwise, <see langword="false"/>.</returns>
//         public static bool TryParse(
// #if NETCOREAPP3_0_OR_GREATER
//             [global::System.Diagnostics.CodeAnalysis.NotNullWhen(true)]
// #endif
//             string? name,
//             out global::NetEscapades.EnumGenerators.IntegrationTests.EnumInNamespace2 value)
//             => TryParse(name, out value, false, false);
//
//         /// <summary>
//         /// Converts the string representation of the name or numeric value of
//         /// an <see cref="global::NetEscapades.EnumGenerators.IntegrationTests.EnumInNamespace2" /> to the equivalent instance.
//         /// The return value indicates whether the conversion succeeded.
//         /// </summary>
//         /// <param name="name">The string representation of the enumeration name or underlying value to convert</param>
//         /// <param name="value">When this method returns, contains an object of type
//         /// <see cref="global::NetEscapades.EnumGenerators.IntegrationTests.EnumInNamespace2" /> whose
//         /// value is represented by <paramref name="value"/> if the parse operation succeeds.
//         /// If the parse operation fails, contains the default value of the underlying type
//         /// of <see cref="global::NetEscapades.EnumGenerators.IntegrationTests.EnumInNamespace2" />. This parameter is passed uninitialized.</param>
//         /// <param name="ignoreCase"><see langword="true"/> to read value in case insensitive mode; <see langword="false"/> to read value in case sensitive mode.</param>
//         /// <returns><see langword="true"/> if the value parameter was converted successfully; otherwise, <see langword="false"/>.</returns>
//         public static bool TryParse(
// #if NETCOREAPP3_0_OR_GREATER
//             [global::System.Diagnostics.CodeAnalysis.NotNullWhen(true)]
// #endif
//             string? name,
//             out global::NetEscapades.EnumGenerators.IntegrationTests.EnumInNamespace2 value,
//             bool ignoreCase)
//             => TryParse(name, out value, ignoreCase, false);
//
//         /// <summary>
//         /// Converts the string representation of the name or numeric value of
//         /// an <see cref="global::NetEscapades.EnumGenerators.IntegrationTests.EnumInNamespace2" /> to the equivalent instance.
//         /// The return value indicates whether the conversion succeeded.
//         /// </summary>
//         /// <param name="name">The string representation of the enumeration name or underlying value to convert</param>
//         /// <param name="value">When this method returns, contains an object of type
//         /// <see cref="global::NetEscapades.EnumGenerators.IntegrationTests.EnumInNamespace2" /> whose
//         /// value is represented by <paramref name="value"/> if the parse operation succeeds.
//         /// If the parse operation fails, contains the default value of the underlying type
//         /// of <see cref="global::NetEscapades.EnumGenerators.IntegrationTests.EnumInNamespace2" />. This parameter is passed uninitialized.</param>
//         /// <param name="ignoreCase"><see langword="true"/> to read value in case insensitive mode; <see langword="false"/> to read value in case sensitive mode.</param>
//         /// <param name="allowMatchingMetadataAttribute">If <see langword="true"/>, considers the value included in metadata attributes such as
//         /// <c>[Display]</c> attribute when parsing, otherwise only considers the member names.</param>
//         /// <returns><see langword="true"/> if the value parameter was converted successfully; otherwise, <see langword="false"/>.</returns>
//         public static bool TryParse(
// #if NETCOREAPP3_0_OR_GREATER
//             [global::System.Diagnostics.CodeAnalysis.NotNullWhen(true)]
// #endif
//             string? name,
//             out global::NetEscapades.EnumGenerators.IntegrationTests.EnumInNamespace2 value,
//             bool ignoreCase,
//             bool allowMatchingMetadataAttribute)
//                 => ignoreCase
//                     ? TryParseIgnoreCase(name, out value, allowMatchingMetadataAttribute)
//                     : TryParseWithCase(name, out value, allowMatchingMetadataAttribute);
//
//         public static bool TryParse(
// #if NETCOREAPP3_0_OR_GREATER
//             [global::System.Diagnostics.CodeAnalysis.NotNullWhen(true)]
// #endif
//             string? name,
//             out global::NetEscapades.EnumGenerators.IntegrationTests.EnumInNamespace2 value,
//             in EnumParseOptions options)
//         {
//             switch (name)
//             {
//                 case string s when s.Equals(nameof(global::NetEscapades.EnumGenerators.IntegrationTests.EnumInNamespace2.First), options.ComparisonType):
//                     value = global::NetEscapades.EnumGenerators.IntegrationTests.EnumInNamespace2.First;
//                     return true;
//                 case string s when s.Equals(nameof(global::NetEscapades.EnumGenerators.IntegrationTests.EnumInNamespace2.Second), options.ComparisonType):
//                     value = global::NetEscapades.EnumGenerators.IntegrationTests.EnumInNamespace2.Second;
//                     return true;
//                 case string s when s.Equals(nameof(global::NetEscapades.EnumGenerators.IntegrationTests.EnumInNamespace2.Third), options.ComparisonType):
//                     value = global::NetEscapades.EnumGenerators.IntegrationTests.EnumInNamespace2.Third;
//                     return true;
//                 case string s when options.EnableNumberParsing && int.TryParse(name, out var val):
//                     value = (global::NetEscapades.EnumGenerators.IntegrationTests.EnumInNamespace2)val;
//                     return true;
//                 default:
//                     value = default;
//                     return false;
//             }
//             
//         }
//         private static bool TryParseIgnoreCase(
// #if NETCOREAPP3_0_OR_GREATER
//             [global::System.Diagnostics.CodeAnalysis.NotNullWhen(true)]
// #endif
//             string? name,
//             out global::NetEscapades.EnumGenerators.IntegrationTests.EnumInNamespace2 value,
//             bool allowMatchingMetadataAttribute)
//         {
//
//             switch (name)
//             {
//                 case string s when s.Equals(nameof(global::NetEscapades.EnumGenerators.IntegrationTests.EnumInNamespace2.First), global::System.StringComparison.OrdinalIgnoreCase):
//                     value = global::NetEscapades.EnumGenerators.IntegrationTests.EnumInNamespace2.First;
//                     return true;
//                 case string s when s.Equals(nameof(global::NetEscapades.EnumGenerators.IntegrationTests.EnumInNamespace2.Second), global::System.StringComparison.OrdinalIgnoreCase):
//                     value = global::NetEscapades.EnumGenerators.IntegrationTests.EnumInNamespace2.Second;
//                     return true;
//                 case string s when s.Equals(nameof(global::NetEscapades.EnumGenerators.IntegrationTests.EnumInNamespace2.Third), global::System.StringComparison.OrdinalIgnoreCase):
//                     value = global::NetEscapades.EnumGenerators.IntegrationTests.EnumInNamespace2.Third;
//                     return true;
//                 case string s when int.TryParse(name, out var val):
//                     value = (global::NetEscapades.EnumGenerators.IntegrationTests.EnumInNamespace2)val;
//                     return true;
//                 default:
//                     value = default;
//                     return false;
//             }
//         }
//
//         private static bool TryParseWithCase(
// #if NETCOREAPP3_0_OR_GREATER
//             [global::System.Diagnostics.CodeAnalysis.NotNullWhen(true)]
// #endif
//             string? name,
//             out global::NetEscapades.EnumGenerators.IntegrationTests.EnumInNamespace2 value,
//             bool allowMatchingMetadataAttribute)
//         {
//
//             switch (name)
//             {
//                 case nameof(global::NetEscapades.EnumGenerators.IntegrationTests.EnumInNamespace2.First):
//                     value = global::NetEscapades.EnumGenerators.IntegrationTests.EnumInNamespace2.First;
//                     return true;
//                 case nameof(global::NetEscapades.EnumGenerators.IntegrationTests.EnumInNamespace2.Second):
//                     value = global::NetEscapades.EnumGenerators.IntegrationTests.EnumInNamespace2.Second;
//                     return true;
//                 case nameof(global::NetEscapades.EnumGenerators.IntegrationTests.EnumInNamespace2.Third):
//                     value = global::NetEscapades.EnumGenerators.IntegrationTests.EnumInNamespace2.Third;
//                     return true;
//                 case string s when int.TryParse(name, out var val):
//                     value = (global::NetEscapades.EnumGenerators.IntegrationTests.EnumInNamespace2)val;
//                     return true;
//                 default:
//                     value = default;
//                     return false;
//             }
//         }
//
// #if NETCOREAPP && !NETCOREAPP2_0 && !NETCOREAPP1_1 && !NETCOREAPP1_0
//         /// <summary>
//         /// Converts the string representation of the name or numeric value of
//         /// an <see cref="global::NetEscapades.EnumGenerators.IntegrationTests.EnumInNamespace2" /> to the equivalent instance.
//         /// </summary>
//         /// <param name="name">The case-sensitive string representation of the enumeration name or underlying value to convert</param>
//         /// <returns>An object of type <see cref="global::NetEscapades.EnumGenerators.IntegrationTests.EnumInNamespace2" /> whose
//         /// value is represented by <paramref name="name"/></returns>
//         public static global::NetEscapades.EnumGenerators.IntegrationTests.EnumInNamespace2 Parse(
// #if NETCOREAPP3_0_OR_GREATER
//             [global::System.Diagnostics.CodeAnalysis.NotNullWhen(true)]
// #endif
//             in global::System.ReadOnlySpan<char> name)
//                 => TryParse(name, out var value, false, false) ? value : ThrowValueNotFound(name.ToString());
//
//         /// <summary>
//         /// Converts the string representation of the name or numeric value of
//         /// an <see cref="global::NetEscapades.EnumGenerators.IntegrationTests.EnumInNamespace2" /> to the equivalent instance.
//         /// </summary>
//         /// <param name="name">The case-sensitive string representation of the enumeration name or underlying value to convert</param>
//         /// <param name="ignoreCase"><see langword="true"/> to read value in case insensitive mode; <see langword="false"/> to read value in case sensitive mode.</param>
//         /// <returns>An object of type <see cref="global::NetEscapades.EnumGenerators.IntegrationTests.EnumInNamespace2" /> whose
//         /// value is represented by <paramref name="name"/></returns>
//         public static global::NetEscapades.EnumGenerators.IntegrationTests.EnumInNamespace2 Parse(
// #if NETCOREAPP3_0_OR_GREATER
//             [global::System.Diagnostics.CodeAnalysis.NotNullWhen(true)]
// #endif
//             in global::System.ReadOnlySpan<char> name,
//             bool ignoreCase)
//                 => TryParse(name, out var value, ignoreCase, false) ? value : ThrowValueNotFound(name.ToString());
//
//         /// <summary>
//         /// Converts the string representation of the name or numeric value of
//         /// an <see cref="global::NetEscapades.EnumGenerators.IntegrationTests.EnumInNamespace2" /> to the equivalent instance.
//         /// </summary>
//         /// <param name="name">The case-sensitive string representation of the enumeration name or underlying value to convert</param>
//         /// <param name="ignoreCase"><see langword="true"/> to read value in case insensitive mode; <see langword="false"/> to read value in case sensitive mode.</param>
//         /// <param name="allowMatchingMetadataAttribute">If <see langword="true"/>, considers the value included in metadata attributes such as
//         /// <c>[Display]</c> attribute when parsing, otherwise only considers the member names.</param>
//         /// <returns>An object of type <see cref="global::NetEscapades.EnumGenerators.IntegrationTests.EnumInNamespace2" /> whose
//         /// value is represented by <paramref name="name"/></returns>
//         public static global::NetEscapades.EnumGenerators.IntegrationTests.EnumInNamespace2 Parse(
// #if NETCOREAPP3_0_OR_GREATER
//             [global::System.Diagnostics.CodeAnalysis.NotNullWhen(true)]
// #endif
//             in global::System.ReadOnlySpan<char> name,
//             bool ignoreCase,
//             bool allowMatchingMetadataAttribute)
//                 => TryParse(name, out var value, ignoreCase, allowMatchingMetadataAttribute) ? value : ThrowValueNotFound(name.ToString());
//
//         /// <summary>
//         /// Converts the span representation of the name or numeric value of
//         /// an <see cref="global::NetEscapades.EnumGenerators.IntegrationTests.EnumInNamespace2" /> to the equivalent instance.
//         /// The return value indicates whether the conversion succeeded.
//         /// </summary>
//         /// <param name="name">The span representation of the enumeration name or underlying value to convert</param>
//         /// <param name="value">When this method returns, contains an object of type
//         /// <see cref="global::NetEscapades.EnumGenerators.IntegrationTests.EnumInNamespace2" /> whose
//         /// value is represented by <paramref name="value"/> if the parse operation succeeds.
//         /// If the parse operation fails, contains the default value of the underlying type
//         /// of <see cref="global::NetEscapades.EnumGenerators.IntegrationTests.EnumInNamespace2" />. This parameter is passed uninitialized.</param>
//         /// <returns><see langword="true"/> if the value parameter was converted successfully; otherwise, <see langword="false"/>.</returns>
//         public static bool TryParse(
// #if NETCOREAPP3_0_OR_GREATER
//             [global::System.Diagnostics.CodeAnalysis.NotNullWhen(true)]
// #endif
//             in global::System.ReadOnlySpan<char> name,
//             out global::NetEscapades.EnumGenerators.IntegrationTests.EnumInNamespace2 value)
//             => TryParse(name, out value, false, false);
//
//         /// <summary>
//         /// Converts the span representation of the name or numeric value of
//         /// an <see cref="global::NetEscapades.EnumGenerators.IntegrationTests.EnumInNamespace2" /> to the equivalent instance.
//         /// The return value indicates whether the conversion succeeded.
//         /// </summary>
//         /// <param name="name">The span representation of the enumeration name or underlying value to convert</param>
//         /// <param name="value">When this method returns, contains an object of type
//         /// <see cref="global::NetEscapades.EnumGenerators.IntegrationTests.EnumInNamespace2" /> whose
//         /// value is represented by <paramref name="value"/> if the parse operation succeeds.
//         /// If the parse operation fails, contains the default value of the underlying type
//         /// of <see cref="global::NetEscapades.EnumGenerators.IntegrationTests.EnumInNamespace2" />. This parameter is passed uninitialized.</param>
//         /// <param name="ignoreCase"><see langword="true"/> to read value in case insensitive mode; <see langword="false"/> to read value in case sensitive mode.</param>
//         /// <returns><see langword="true"/> if the value parameter was converted successfully; otherwise, <see langword="false"/>.</returns>
//         public static bool TryParse(
// #if NETCOREAPP3_0_OR_GREATER
//             [global::System.Diagnostics.CodeAnalysis.NotNullWhen(true)]
// #endif
//             in global::System.ReadOnlySpan<char> name,
//             out global::NetEscapades.EnumGenerators.IntegrationTests.EnumInNamespace2 value,
//             bool ignoreCase)
//             => TryParse(name, out value, ignoreCase, false);
//
//         /// <summary>
//         /// Converts the span representation of the name or numeric value of
//         /// an <see cref="global::NetEscapades.EnumGenerators.IntegrationTests.EnumInNamespace2" /> to the equivalent instance.
//         /// The return value indicates whether the conversion succeeded.
//         /// </summary>
//         /// <param name="name">The span representation of the enumeration name or underlying value to convert</param>
//         /// <param name="result">When this method returns, contains an object of type
//         /// <see cref="global::NetEscapades.EnumGenerators.IntegrationTests.EnumInNamespace2" /> whose
//         /// value is represented by <paramref name="result"/> if the parse operation succeeds.
//         /// If the parse operation fails, contains the default value of the underlying type
//         /// of <see cref="global::NetEscapades.EnumGenerators.IntegrationTests.EnumInNamespace2" />. This parameter is passed uninitialized.</param>
//         /// <param name="ignoreCase"><see langword="true"/> to read value in case insensitive mode; <see langword="false"/> to read value in case sensitive mode.</param>
//         /// <param name="allowMatchingMetadataAttribute">If <see langword="true"/>, considers the value included in metadata attributes such as
//         /// <c>[Display]</c> attribute when parsing, otherwise only considers the member names.</param>
//         /// <returns><see langword="true"/> if the value parameter was converted successfully; otherwise, <see langword="false"/>.</returns>
//         public static bool TryParse(
// #if NETCOREAPP3_0_OR_GREATER
//             [global::System.Diagnostics.CodeAnalysis.NotNullWhen(true)]
// #endif
//             in global::System.ReadOnlySpan<char> name,
//             out global::NetEscapades.EnumGenerators.IntegrationTests.EnumInNamespace2 result,
//             bool ignoreCase,
//             bool allowMatchingMetadataAttribute)
//                 => ignoreCase
//                     ? TryParseIgnoreCase(in name, out result, allowMatchingMetadataAttribute)
//                     : TryParseWithCase(in name, out result, allowMatchingMetadataAttribute);
//
//         private static bool TryParseIgnoreCase(
// #if NETCOREAPP3_0_OR_GREATER
//             [global::System.Diagnostics.CodeAnalysis.NotNullWhen(true)]
// #endif
//             in global::System.ReadOnlySpan<char> name,
//             out global::NetEscapades.EnumGenerators.IntegrationTests.EnumInNamespace2 result,
//             bool allowMatchingMetadataAttribute)
//         {
//             switch (name)
//             {
//                 case global::System.ReadOnlySpan<char> current when global::System.MemoryExtensions.Equals(current, nameof(global::NetEscapades.EnumGenerators.IntegrationTests.EnumInNamespace2.First), global::System.StringComparison.OrdinalIgnoreCase):
//                     result = global::NetEscapades.EnumGenerators.IntegrationTests.EnumInNamespace2.First;
//                     return true;
//                 case global::System.ReadOnlySpan<char> current when global::System.MemoryExtensions.Equals(current, nameof(global::NetEscapades.EnumGenerators.IntegrationTests.EnumInNamespace2.Second), global::System.StringComparison.OrdinalIgnoreCase):
//                     result = global::NetEscapades.EnumGenerators.IntegrationTests.EnumInNamespace2.Second;
//                     return true;
//                 case global::System.ReadOnlySpan<char> current when global::System.MemoryExtensions.Equals(current, nameof(global::NetEscapades.EnumGenerators.IntegrationTests.EnumInNamespace2.Third), global::System.StringComparison.OrdinalIgnoreCase):
//                     result = global::NetEscapades.EnumGenerators.IntegrationTests.EnumInNamespace2.Third;
//                     return true;
//                 case global::System.ReadOnlySpan<char> current when int.TryParse(name, out var numericResult):
//                     result = (global::NetEscapades.EnumGenerators.IntegrationTests.EnumInNamespace2)numericResult;
//                     return true;
//                 default:
//                     result = default;
//                     return false;
//             }
//         }
//
//         private static bool TryParseWithCase(
// #if NETCOREAPP3_0_OR_GREATER
//             [global::System.Diagnostics.CodeAnalysis.NotNullWhen(true)]
// #endif
//             in global::System.ReadOnlySpan<char> name,
//             out global::NetEscapades.EnumGenerators.IntegrationTests.EnumInNamespace2 result,
//             bool allowMatchingMetadataAttribute)
//         {
//             switch (name)
//             {
//                 case global::System.ReadOnlySpan<char> current when global::System.MemoryExtensions.Equals(current, nameof(global::NetEscapades.EnumGenerators.IntegrationTests.EnumInNamespace2.First), global::System.StringComparison.Ordinal):
//                     result = global::NetEscapades.EnumGenerators.IntegrationTests.EnumInNamespace2.First;
//                     return true;
//                 case global::System.ReadOnlySpan<char> current when global::System.MemoryExtensions.Equals(current, nameof(global::NetEscapades.EnumGenerators.IntegrationTests.EnumInNamespace2.Second), global::System.StringComparison.Ordinal):
//                     result = global::NetEscapades.EnumGenerators.IntegrationTests.EnumInNamespace2.Second;
//                     return true;
//                 case global::System.ReadOnlySpan<char> current when global::System.MemoryExtensions.Equals(current, nameof(global::NetEscapades.EnumGenerators.IntegrationTests.EnumInNamespace2.Third), global::System.StringComparison.Ordinal):
//                     result = global::NetEscapades.EnumGenerators.IntegrationTests.EnumInNamespace2.Third;
//                     return true;
//                 case global::System.ReadOnlySpan<char> current when int.TryParse(name, out var numericResult):
//                     result = (global::NetEscapades.EnumGenerators.IntegrationTests.EnumInNamespace2)numericResult;
//                     return true;
//                 default:
//                     result = default;
//                     return false;
//             }
//         }
// #endif
//
//         /// <summary>
//         /// Retrieves an array of the values of the members defined in
//         /// <see cref="global::NetEscapades.EnumGenerators.IntegrationTests.EnumInNamespace2" />.
//         /// Note that this returns a new array with every invocation, so
//         /// should be cached if appropriate.
//         /// </summary>
//         /// <returns>An array of the values defined in <see cref="global::NetEscapades.EnumGenerators.IntegrationTests.EnumInNamespace2" /></returns>
//         public static global::NetEscapades.EnumGenerators.IntegrationTests.EnumInNamespace2[] GetValues()
//         {
//             return new[]
//             {
//                 global::NetEscapades.EnumGenerators.IntegrationTests.EnumInNamespace2.First,
//                 global::NetEscapades.EnumGenerators.IntegrationTests.EnumInNamespace2.Second,
//                 global::NetEscapades.EnumGenerators.IntegrationTests.EnumInNamespace2.Third,
//             };
//         }
//
//         /// <summary>
//         /// Retrieves an array of the underlying-values of the members defined in
//         /// <see cref="global::NetEscapades.EnumGenerators.IntegrationTests.EnumInNamespace2" />.
//         /// Note that this returns a new array with every invocation, so
//         /// should be cached if appropriate.
//         /// </summary>
//         /// <returns>An array of the underlying-values defined in <see cref="global::NetEscapades.EnumGenerators.IntegrationTests.EnumInNamespace2" /></returns>
//         public static int[] GetValuesAsUnderlyingType()
//         {
//             return new[]
//             {
//                 (int) global::NetEscapades.EnumGenerators.IntegrationTests.EnumInNamespace2.First,
//                 (int) global::NetEscapades.EnumGenerators.IntegrationTests.EnumInNamespace2.Second,
//                 (int) global::NetEscapades.EnumGenerators.IntegrationTests.EnumInNamespace2.Third,
//             };
//         }
//
//         /// <summary>
//         /// Retrieves an array of the names of the members defined in
//         /// <see cref="global::NetEscapades.EnumGenerators.IntegrationTests.EnumInNamespace2" />.
//         /// Note that this returns a new array with every invocation, so
//         /// should be cached if appropriate.
//         /// </summary>
//         /// <returns>An array of the names of the members defined in <see cref="global::NetEscapades.EnumGenerators.IntegrationTests.EnumInNamespace2" /></returns>
//         public static string[] GetNames()
//         {
//             return new[]
//             {
//                 nameof(global::NetEscapades.EnumGenerators.IntegrationTests.EnumInNamespace2.First),
//                 nameof(global::NetEscapades.EnumGenerators.IntegrationTests.EnumInNamespace2.Second),
//                 nameof(global::NetEscapades.EnumGenerators.IntegrationTests.EnumInNamespace2.Third),
//             };
//         }
//         // }
//     }
// #pragma warning restore CS0612 // Ignore usages of obsolete members or enums
// #pragma warning restore CS0618 // Ignore usages of obsolete members or enums
// }
//
// namespace NetEscapades.EnumGenerators
// {
//     /// <summary>
//     /// Defines the options use when parsing enums using members provided by NetEscapades.EnumGenerator.
//     /// </summary>
//     public struct EnumParseOptions
//     {
//         private bool? _enableNumberParsing;
//         private StringComparison? _comparisonType;
//
//         /// <summary>
//         /// Gets or sets a value defining whether numbers should be parsed as a fallback when
//         /// other parsing fails 
//         /// </summary>
//         /// <remarks>
//         /// By default, it's set to <see langword="false"/>, and numbers will be parsed as well as names.
//         /// </remarks>
//         public bool EnableNumberParsing
//         {
//             readonly get => _enableNumberParsing ?? true;
//             set => _enableNumberParsing = value;
//         }
//
//         /// <summary>
//         /// Gets or sets the <see cref="global::System.StringComparison"/> to use during parsing.  
//         /// </summary>
//         /// <remarks>
//         /// By default, it's set to <see cref="global::System.StringComparison.Ordinal"/>, and a case-sensitive
//         /// comparison will be used.
//         /// </remarks>
//         public StringComparison ComparisonType
//         {
//             readonly get => _comparisonType ?? StringComparison.Ordinal;
//             set => _comparisonType = value;
//         }
//
//         /// <summary>
//         /// Gets or sets whether the value of any metadata value attributes
//         /// values applied to an enum should be used as the parse value for an enum.
//         /// </summary>
//         /// <remarks>
//         /// By default, it's set to <see langword="false"/>, so the value of any metadata attributes on the
//         /// enum values are ignored, depending on the applicable
//         /// <see cref="global::NetEscapades.EnumGenerators.MetadataSource"/> for the enum.
//         /// </remarks>
//         public bool UseMetadataAttributes { readonly get; set; }
//     }
//
//     /// <summary>
//     /// Options to apply when calling ToStringFast on an enum. 
//     /// </summary>
//     public struct ToStringFastOptions
//     {
//         /// <summary>
//         /// Gets or sets whether the value of any <see cref="global::System.ComponentModel.DataAnnotations.DisplayAttribute"/>
//         /// values applied to an enum should be used as the `ToString()` value for an enum.
//         /// </summary>
//         /// <remarks>
//         /// By default, it's set to <see langword="false"/>, so the value of any <c>[Display]</c> attributes on the
//         /// enum values are ignored. Takes precedence over <see cref="UseDescriptionAttribute"/>. 
//         /// </remarks>
//         public bool UseDisplayAttribute { readonly get; set; }
//
//         /// <summary>
//         /// Gets or sets whether the value of any <see cref="global::System.ComponentModel.DescriptionAttribute"/>
//         /// values applied to an enum should be used as the parse value for an enum.
//         /// </summary>
//         /// <remarks>
//         /// By default, it's set to <see langword="false"/>, so the value of any <c>[Description]</c> attributes on the
//         /// enum values are ignored. 
//         /// </remarks>
//         public bool UseDescriptionAttribute { readonly get; set; }
//     }
//
//     /// <summary>
//     /// Transform to apply when calling <c>ToStringFast</c> 
//     /// </summary>
//     public enum ToStringFastTransform
//     {
//         /// <summary>
//         /// Don't apply a transform to the ToStringFast() result.
//         /// </summary>
//         None,
//
//         /// <summary>
//         /// Call <see cref="string.ToLowerInvariant"/> on the ToStringFast() result.
//         /// </summary>
//         LowerInvariant,
//
//         /// <summary>
//         /// Call <see cref="string.ToUpperInvariant"/> on the ToStringFast() result.
//         /// </summary>
//         UpperInvariant,
//     }
// }